# Generated by Django 6.0 on 2025-12-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
