# Generated by Django 6.0 on 2025-12-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_employee_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='card_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
